AllCops:
  Include:
    - 'lib/**/*.rb'
  Exclude:
    - 'scripts/**/*'
    - 'spec/**/*'
    - 'vendor/**/*'
    - Gemfile
    - Rakefile

# These short variable names make sense as exceptions to the rule, but generally I think short variable names do hurt readability
Naming/MethodParameterName:
  AllowedNames:
    - vm
    - dc
    - s
    - x
    - f

#new cops:
Lint/DuplicateRegexpCharacterClassElement: # (new in 1.1)
  Enabled: true
Lint/EmptyBlock: # (new in 1.1)
  Enabled: true
Lint/ToEnumArguments: # (new in 1.1)
  Enabled: true
Lint/UnmodifiedReduceAccumulator: # (new in 1.1)
  Enabled: true
Style/ArgumentsForwarding: # (new in 1.1)
  Enabled: false
Style/DocumentDynamicEvalDefinition: # (new in 1.1)
  Enabled: true
Style/SwapValues: # (new in 1.1)
  Enabled: false

#disabled

Metrics/AbcSize:
  Max: 77
Metrics/ClassLength:
  Max: 430
Metrics/CyclomaticComplexity:
  Max: 14
Metrics/MethodLength:
  Max: 48
Metrics/PerceivedComplexity:
  Max: 14
Metrics/ParameterLists:
  Max: 6
Layout/LineLength:
  Max: 220